FROM node:20-alpine AS frontend-build

WORKDIR /app

COPY web/package*.json ./
RUN npm install

COPY web/. .
RUN npm run build

FROM nginx:alpine

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=frontend-build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]